// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC--Zb3O4xZ-HPQVFMnVgeCb6qnSnMYhiU',
    appId: '1:225491597745:web:0ca444bb0bec98ebbd6590',
    messagingSenderId: '225491597745',
    projectId: 'gleamday-d5cc8',
    authDomain: 'gleamday-d5cc8.firebaseapp.com',
    storageBucket: 'gleamday-d5cc8.firebasestorage.app',
    measurementId: 'G-RB2Y59P6G8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzVErzvcatm0A3BURp0hD5Mrdpm6LfBu0',
    appId: '1:225491597745:android:d31287b43242eeb8bd6590',
    messagingSenderId: '225491597745',
    projectId: 'gleamday-d5cc8',
    storageBucket: 'gleamday-d5cc8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBO4TNsgw6mzVyncA3UkKxYSPyZoaEYpm0',
    appId: '1:225491597745:ios:fe615451c4930cf8bd6590',
    messagingSenderId: '225491597745',
    projectId: 'gleamday-d5cc8',
    storageBucket: 'gleamday-d5cc8.firebasestorage.app',
    iosBundleId: 'com.hyunchae29.gleamday.gleamDay',
  );
}
